### ISSUE TITLE
Session duration reported incorrectly

### ISSUE THREAD

**Issue by stuart-provelabs** [Microsoft/mobile-center-app-xamarin#1]
We have an app on both iOS and Android using Xamarin Forms. All metrics appear to be fine except session duration. Every session is reported in the 0s-10s band with an average session length of < 1s.

**Comment by lumaxis** [comment]
Hey @stuart-provelabs! Please report this issue over at [Microsoft/mobile-center-sdk-dotnet](https://github.com/Microsoft/mobile-center-sdk-dotnet/issues/new) as this is the repo for a mobile app demonstrating how to use Mobile Center, thanks!
